/**
 * The Echo Health analytics taxonomy — the single source of truth for event
 * names and their payloads, shared by client and server capture.
 *
 * ## Why this file exists
 *
 * The original instrumentation was generated by a wizard and then drifted: the
 * saved PostHog insights measured `user_signed_up`, `user_role_selected` and
 * `therapist_onboarding_completed`, none of which the app has emitted since the
 * Auth0 migration renamed them. Three of five dashboards rendered flat zeros,
 * which reads as "no signups" rather than "wrong event name" — the most
 * expensive kind of analytics bug, because it looks like data.
 *
 * Names live here as constants so that renaming an event is a compile error at
 * every call site rather than a dashboard that quietly goes flat.
 *
 * ## The privacy rule (read before adding an event)
 *
 * This is a mental-health platform. The *content* of what a person writes or
 * feels never goes to a third-party analytics vendor — not the text, not a
 * score, not a category. What is allowed is that an action happened, and
 * structural facts about it (counts, durations, prices, roles).
 *
 * Concretely:
 *  - `journal_entry_created` carries no text and no length.
 *  - `mood_logged` carries no mood value. A mood score against a stable person
 *    id is a longitudinal record of someone's mental state.
 *  - `message_sent` carries direction and thread position, never the body.
 *  - Risk-scanner outcomes are NOT captured at all. A `risk_alert` is the most
 *    sensitive row in the database; its existence against a person id would say
 *    "this individual was flagged as in crisis". It stays in Postgres, behind
 *    RLS, where the clinical team reads it. See AGENTS.md § Clinical risk.
 *  - Provider identifiers (`therapist_id`) ARE allowed: a therapist is a
 *    business entity here, and directory conversion is unmeasurable without it.
 *    Patient identifiers are not.
 *
 * If a new event needs a property and you are unsure, the test is: would this
 * be acceptable in a breach notification? If not, aggregate it or drop it.
 */

export const ANALYTICS_EVENTS = {
  // ── Acquisition ────────────────────────────────────────────────────────────
  /** Client-side intent: the visitor clicked sign-up and is leaving for Auth0. */
  SIGN_UP_STARTED: "sign_up_started",
  /** Client-side intent: the visitor clicked sign-in and is leaving for Auth0. */
  SIGN_IN_STARTED: "sign_in_started",
  /**
   * Server-side truth: a session exists at `/post-login`.
   *
   * Under Universal Login the browser leaves the app to authenticate, so the
   * client never observes success — the intent events above cannot tell a
   * completed login from an abandoned one. This is the only event that can
   * close that funnel, and it is why the previous instrumentation could not
   * measure conversion at all.
   */
  USER_AUTHENTICATED: "user_authenticated",
  /** Server-side: a role was assigned via `/api/user/set-role`. */
  USER_ROLE_SELECTED: "user_role_selected",

  // ── Client activation ──────────────────────────────────────────────────────
  /** @unwired Directory browsing — see the wiring note at the bottom of this file. */
  THERAPIST_DIRECTORY_VIEWED: "therapist_directory_viewed",
  /** @unwired */
  THERAPIST_PROFILE_VIEWED: "therapist_profile_viewed",
  SESSION_BOOKED: "session_booked",
  /** Emitted on a genuine transition INTO `cancelled`, never on a re-save. */
  SESSION_CANCELLED: "session_cancelled",

  // ── The session itself (the product's core moment) ─────────────────────────
  VIDEO_ROOM_OPENED: "video_room_opened",
  /** Peer connection reached `connected` — the call actually works. */
  VIDEO_CONNECTED: "video_connected",
  /** Terminal failure before or after connect. Carries a reason, never media. */
  VIDEO_FAILED: "video_failed",

  // ── Engagement between sessions (existence only, never content) ────────────
  MESSAGE_SENT: "message_sent",
  /** @unwired Would go in `createMoodLogAction` — value must NOT be included. */
  MOOD_LOGGED: "mood_logged",
  /** @unwired Would go in `createJournalEntryAction` — no text, no length. */
  JOURNAL_ENTRY_CREATED: "journal_entry_created",
  GOAL_CREATED: "goal_created",
  GOAL_COMPLETED: "goal_completed",

  // ── Supply side (therapists) ───────────────────────────────────────────────
  /** @unwired Would go at the top of `app/onboarding/therapist/page.tsx`. */
  THERAPIST_ONBOARDING_STARTED: "therapist_onboarding_started",
  THERAPIST_KYC_SUBMITTED: "therapist_kyc_submitted",
  THERAPIST_KYC_REVIEWED: "therapist_kyc_reviewed",
  THERAPIST_KYC_DOCUMENT_REVIEWED: "therapist_kyc_document_reviewed",
  /** @unwired Would go in `saveMyAvailabilityAction`. */
  THERAPIST_AVAILABILITY_SAVED: "therapist_availability_saved",
  /** @unwired Would go in `createClinicalNoteAction` — count only, no content. */
  CLINICAL_NOTE_CREATED: "clinical_note_created",

  // ── Money ──────────────────────────────────────────────────────────────────
  PLAN_UPGRADE_CLICKED: "plan_upgrade_clicked",
  /** Fired only once Paystack accepts the transaction — checkout reached, not attempted. */
  PAYMENT_INITIALIZED: "payment_initialized",
  PAYMENT_SUCCEEDED: "payment_succeeded",
  PAYMENT_FAILED: "payment_failed",
  PROMO_CODE_REDEEMED: "promo_code_redeemed",

  // ── Support ────────────────────────────────────────────────────────────────
  CHAT_MESSAGE_SENT: "chat_message_sent",
} as const;

/**
 * ## `@unwired` means declared here but NOT emitted anywhere yet
 *
 * They are named up front so the taxonomy reflects the product rather than
 * whatever happened to get instrumented first, and so a later wiring pass uses
 * the agreed name instead of inventing a synonym.
 *
 * **Do not build a saved insight on an `@unwired` event.** That is precisely
 * how the previous instrumentation failed: dashboards were created for
 * `user_signed_up`, `user_role_selected` and `therapist_onboarding_completed`,
 * the code emitted none of them, and the charts read as a flat zero — which
 * looks like "nobody signed up" rather than "this chart is broken". Delete the
 * tag in the same commit that adds the capture call.
 */

export type AnalyticsEvent =
  (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];

/**
 * Person properties. Deliberately NOT email or name.
 *
 * Identification is by Auth0 `sub` alone. PostHog therefore holds pseudonymous
 * ids plus coarse segments; joining back to a real person requires this app's
 * own database, which is access-controlled and audited. Previously every person
 * profile carried email and name, which made the analytics project a list of
 * identifiable people using a mental-health service.
 */
export interface PersonProperties {
  role?: "client" | "therapist" | "admin" | "none";
  plan?: string;
  /** Signup month (`2026-07`), for cohorting without a precise timestamp. */
  signup_cohort?: string;
}
